### ISSUE TITLE
Occasional camera frame corrupted, causing entire run to fail processing

### ISSUE THREAD

**Issue by djcranshaw** [picoexperiment/AutoBub3hs#12]
In the 40l-24 series, run 20240930_0 fails processing due to the following error somewhere in OpenCV:

libpng error: PNG input buffer is incomplete
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.9.0) /tmp/ebuser/avx2/OpenCV/4.9.0/gccflexiblas-2023a/opencv-4.9.0/modules/core/src/matrix_expressions.cpp:32: error: (-5:Bad argument) One or more matrix operands are empty. in function 'checkOperandsExist'

I've traced this down to the fact that these three images are "corrupted" (at least, the .verify() call fails in PIL version 10.0.1, but MS photos seems to open them fine).

20240930_0/14/Images/cam3_image46.png
20240930_0/26/Images/cam3_image31.png
20240930_0/31/Images/cam3_image38.png

I know this is the issue because when I replace these three frames with the frames before them using the following, processing succeeds (nobody panic, I did this with a copy of this run living safely in a separate directory, not the real data).

unzip "20240930_0.zip" "20240930_0/14/Images/cam3_image45.png" -d .
mv 20240930_0/14/Images/cam3_image45.png 20240930_0/14/Images/cam3_image46.png
zip 20240930_0.zip 20240930_0/14/Images/cam3_image46.png
<likewise for the other two frames>

As far as I know, only autobub actually reads the raw images, but I might be wrong about that. Also I don't know if this is related to the recent changes to the camserver(s). So there are two things that need to be done to resolve this issue.
1. Diagnose and resolve whatever is causing corrupted pngs to be written to disk
2. Hotfix autobub to be more robust against corrupted pngs.

**Comment by jeremysavoie** [comment]
Currently, Autobub is the only optics software that looks at the raw images. We may have more if we start using the shadow analysis, but that is in the distant future.

I don't believe it is associated to the camservers since it seems that it happens for cam3 which is on camserver 1, the server that was not affected by the issues. I know image corruption was a thing, but I expected it to just skip the frames. Or maybe that was when the camera skips a frame. We should check with Babar to get a quick fix for now.

**Comment by b-ali** [comment]
Hi @djcranshaw,

I am working with raw images (python autobub stuff). I can confirm these images are corrupt.

20240930_0/14/Images/cam3_image46.png
20240930_0/26/Images/cam3_image31.png
20240930_0/31/Images/cam3_image38.png

In openCV, imdecode() method is used to decode the image. It returns Null or empty matrix in case the buffer is too short or contains invalid data. In C++ autobub code, there is no check to skip such images. https://github.com/picoexperiment/AutoBub3hs/blob/master/ParseFolder/ZipParser.cpp#L222
I think such cases were not expected.

2) Hotfix autobub to be more robust against corrupted pngs.

--> It is not straight forward. Autobub first trained on the first two images of each event. Then, it try to locate the bubble for each image of each camera and event. Basically, the ZipParser::GetImage(..) method is called multiple times. If we add a check in that method, it will most probably break the code. Easiest solution is to skip the event. But if you really want to analyse such events, I can try a patch for such cases.

**Comment by djcranshaw** [comment]
Colin made a good suggestion that maybe these images are only corrupt on Graham because of a failed copy from the gateway. Unfortunately that's not the case, they are corrupt on the gateway as well.

It would be really unfortunate to have to throw out an entire event just from one missing frame in one camera. Wrapping a try-catch around L222 is trivial, I guess the real work comes in gracefully handling the missing frame everywhere GetImage is called. I would be in favour of at least trying to make the necessary changes to salvage the event - we don't know how common this kind of thing will be going forward and we'd like to minimize our dead-time as much as possible.

**Comment by b-ali** [comment]
Ok sure. I'll try to fix it and let you know.

**Comment by b-ali** [comment]
@djcranshaw I've pushed my changes to a new branch
https://github.com/picoexperiment/AutoBub3hs/tree/fixCorruptImg
Please try it and let me know.

**Comment by djcranshaw** [comment]
@b-ali Thanks for this. It took me a minute to figure out how to switch processing to this branch. The code changes look good and it seems to have solved the processing failure previously observed. If you open a PR I'm happy to approve.

**Comment by djcranshaw** [comment]
@b-ali I pushed a very small fix to this branch. I checked whether processing would crash if Frame 30 or Frame 31 were corrupted, and it turned out to crash exactly if Frame 30 was corrupted but Frame 31 wasn't. The reason was, when Trainer.cpp sees that Frame 30 is corrupted, the variable isThisAGoodEvent is (correctly) set to false, but then when it sees Frame 31 is not corrupted, it (incorrectly) sets it back to True, and then an error occurs downstream because Frame 30 is missing. The fix was easy, I just moved setting isThisAGoodEvent to true outside the training sequence loop. Please have a look to check that this make sense, and if you agree that it's fine, please open a PR and we will get this merged.

**Comment by djcranshaw** [comment]
Merged, and camdaq issue captured [here](https://github.com/orgs/picoexperiment/projects/2/views/7?pane=issue&itemId=87993521)
